project:
  type: website

website:
  page-navigation: true
  title: "Course title"
  description: "Course description"
  site-url: "https://sta210-s22.github.io/website/"
  favicon: "images/favicon.ico"

  repo-url: https://github.com/sta210-s22/website
  repo-actions: [edit, issue]

  open-graph: true

  twitter-card:
    creator: "@minebocek"
    image: "images/twitter-card.png"

  page-footer:
    left: "&copy; 2025 üêä [W. Edwin Harris](https://weharris.me)"
    center: "üìä [The Statistics Lab](https://thestatisticslab.com)"
    right: "üöÄ Built with [Quarto](https://quarto.org/)."
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/weharris
        text: "Course GitHub repo"
      - icon: youtube
        href: https://youtube.com/@TheStatisticsLab
        text: "YouTube"
      - icon: discord
        href: https://discord.gg/dnNTE6xhhu
        text: "Join our Discord"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome!
      - href: page-schedule.qmd
        text: Schedule
      - section: "Module info"
        contents:
          - href: module-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Teaching team
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
      - section: "Project"
        contents:
          - href: project-description.qmd
            text: Description
          - href: project-tips-resources.qmd
            text: Tips + resources
      - section: "Weekly materials"
        contents:
          - href: weeks/week-1.qmd
            text: "Week 1"
          - href: weeks/week-2.qmd
            text: "Week 2"
      - section: "Supplemental notes"
        contents:
          - href: supplemental/slr-derivations.qmd
            text: SLR derivations
          - href: supplemental/model-diagnostics-matrix.qmd
            text: Model diagnostics
          - href: supplemental/mlr-matrix.qmd
            text: MLR matrix notation
          - href: supplemental/log-transformations.qmd
            text: Log transformations
          - href: supplemental/model-selection-criteria.qmd
            text: Model selection criteria

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual