project:
  type: website

website:
  page-navigation: true
  title: "Course title"
  description: "Course description"
  site-url: "https://<GithubOrgName>.github.io/website/"
  favicon: "images/favicon.ico"

  repo-url: https://github.com/sta210-s22/website
  repo-actions: [edit, issue]

  open-graph: true

  twitter-card:
    creator: "@EdHarris9000"
    image: "images/twitter-card.png"

  page-footer:
    left: "&copy; 2025 üêä [W. Edwin Harris](https://weharris.me)"
    center: "üìä [The Statistics Lab](https://thestatisticslab.com)"
    right: "üöÄ Built with [Quarto](https://quarto.org/)."
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/weharris
        text: "Course GitHub repo"
      - icon: youtube
        href: https://youtube.com/@TheStatisticsLab
        text: "YouTube"
      - icon: discord
        href: https://discord.gg/dnNTE6xhhu
        text: "Join our Discord"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome!
      - href: page-schedule.qmd
        text: Schedule
      - href: module-syllabus.qmd
        text: Syllabus
      - href: module-links.qmd
        text: Useful links
      - href: module-faq.qmd
        text: FAQ

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual